all:
	gcc sudoku1.c -o sudoku1
	gcc sudoku2.c -o sudoku2
	gcc sudoku3.c -o sudoku3
	g++ sudoku4.cpp -o sudoku4
	gcc sudoku5.c -o sudoku5
	gcc sudoku6.c -o sudoku6
	gcc sudoku7.c -o sudoku7
	gcc sudoku8.c -o sudoku8
	g++ sudoku9.cpp -o sudoku9

clean:
	rm sudoku1 sudoku2 sudoku3 sudoku4 sudoku5 sudoku6 sudoku7 sudoku8 sudoku9 
